# -*- coding: utf-8 -*-
"""TMUpgrade.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kwO1iDrz8vJoPAcySIBwLEZ5GecQ8cJl
"""

# import
from google.colab import files
import pandas as pd
import numpy as np
from datetime import datetime
from openpyxl import Workbook

Workbook.default_style = None

# Upload all the files
def upload_and_load_dataframe(message):
    print(message)
    upload = files.upload()
    file = next(iter(upload))
    df = pd.read_excel(file)
    return file, df

def copy_data(df_guide, df_file):
  df_guide['Donor Id'] = df_file['Supporter ID']
  df_guide['Title'] = df_file['Title']
  df_guide['First Name'] = df_file['First Name']
  df_guide['Last Name'] = df_file['Last Name']
  df_guide['Ethnic'] = df_file['Ethnic']
  df_guide['Gender'] = df_file['Gender']
  df_guide['Street'] = df_file['Mailing Street']
  df_guide['City'] = df_file['Mailing City']
  df_guide['State'] = df_file['Mailing State/Province']
  df_guide['Post Code'] = df_file['Mailing Zip/Postal Code']
  df_guide['Country'] = df_file['Mailing Country']
  df_guide['Home Phone'] = df_file['Home Phone']
  df_guide['Work Phone'] = df_file['Work Phone']
  df_guide['Mobile Phone'] = df_file['Mobile']
  df_guide['Email'] = df_file['Email']
  df_guide['Date of Birth'] = df_file['Birthdate']
  df_guide['National Id'] = df_file['National ID']
  df_guide['Last Pledge Amount'] = df_file['Donation Amount']
  df_guide['Donation Amount'] = df_file['Donation Amount']
  df_guide['Last Pledge Date'] = df_file['Last Donation Date']
  df_guide['Pledge id'] = df_file['Pledge ID']
  df_guide['Pledge Date'] = df_file['Created Date']
  df_guide['Pledge Start Date'] = df_file['Start Date']
  df_guide['Payment Method'] = df_file['Payment Method']
  df_guide['Payment Submethod'] = df_file['Payment Submethod']
  df_guide['Truncated CC'] = df_file['Card Number (Partial Only)']
  df_guide['Expiry Date'] = df_file['Card Expiry']
  df_guide['Frequency'] = df_file['Pledge Frequency']
  df_guide['Campaign'] = '7015g000000UIlXAAW'
  df_guide['Campaign Name'] = 'TM Upgrade SF - UTS'
  df_guide['Description'] = 'TM Upgrade SF - UTS'

  return df_guide.copy()

# mapping
column_format = {
    'Donor Id': [],
    'Title': [],
    'First Name': [],
    'Last Name':[],
    'Ethnic':[],
    'Gender':[],
    'Street':[],
    'City':[],
    'State':[],
    'Post Code':[],
    'Country':[],
    'Home Phone':[],
    'Work Phone':[],
    'Mobile Phone':[],
    'Email':[],
    'Date of Birth':[],
    'National Id':[],
    'Last Pledge Amount':[],
    'Last Cash Amount':[],
    'Last Pledge Date':[],
    'Last Cash Date':[],
    'Pledge id':[],
    'Pledge Date':[],
    'Pledge Start Date':[],
    'Pledge End Date':[],
    'Donation Amount':[],
    'Payment Method':[],
    'Payment Submethod':[],
    'Truncated CC':[],
    'Expiry Date':[],
    'Frequency':[],
    'Cardholder Name':[],
    'Gift Date':[],
    'Campaign':[],
    'Campaign Name':[],
    'Bank Account Holder Name':[],
    'Bank Account Number':[],
    'Description':[],
    'DRTV Time':[],
    'Bank':[],
    'Unique Id':[],
    'Membership No':[],
}

def export_to_excel(df,output_filename):
  df.to_excel(output_filename, index=False)
  files.download(output_filename)

if __name__ == '__main__':

  uploaded_files = []

  file1, TMU_IH_MN_UTS = upload_and_load_dataframe('Upload TMU_IH_MN_UTS file')
  uploaded_files.append((file1, TMU_IH_MN_UTS))
  file2, TMU_IH_MN10_UTS = upload_and_load_dataframe('Upload TMU_IH_MN10_UTS file')
  uploaded_files.append((file2, TMU_IH_MN10_UTS))
  file3, TMU_IH_SM_UTS = upload_and_load_dataframe('Upload TMU_IH_SM_UTS file')
  uploaded_files.append((file3, TMU_IH_SM_UTS))
  file4, TMU_IH_SM10_UTS = upload_and_load_dataframe('Upload TMU_IH_SM10_UTS file')
  uploaded_files.append((file4, TMU_IH_SM10_UTS))
  file5, TMU_IP_MN_UTS = upload_and_load_dataframe('Upload TMU_IP_MN_UTS file')
  uploaded_files.append((file5, TMU_IP_MN_UTS))
  file6, TMU_SG_MN_UTS = upload_and_load_dataframe('Upload TMU_SG_MN_UTS file')
  uploaded_files.append((file6, TMU_SG_MN_UTS))
  file7, TMU_SG_MN10_UTS = upload_and_load_dataframe('Upload TMU_SG_MN10_UTS file')
  uploaded_files.append((file7, TMU_SG_MN10_UTS))
  file8, TMU_SG_SM_UTS = upload_and_load_dataframe('Upload TMU_SG_SM_UTS file')
  uploaded_files.append((file8, TMU_SG_SM_UTS))
  file9, TMU_SG_SM10_UTS = upload_and_load_dataframe('Upload TMU_SG_SM10_UTS file')
  uploaded_files.append((file9, TMU_SG_SM10_UTS))


  df_guide = pd.DataFrame(column_format)

   # Loop through the uploaded files and process them
  for uploaded_file, uploaded_data in uploaded_files:
    current_filename = uploaded_file[:-12]
    output_filename = f'{current_filename}.xlsx'

    # Copy data and process
    processed_data = copy_data(df_guide.copy(), uploaded_data)

    # Export the processed data to Excel with the unique output filename
    export_to_excel(processed_data, output_filename)